### ISSUE TITLE
FSP : Arabic Disc. Text Editor should be start from Right

### ISSUE THREAD

**Issue by Mustafa016** [O16Labs-Khi/HungerAdvisor#191]
https://user-images.githubusercontent.com/83067788/119325554-675bff80-bc9a-11eb-9e1a-8919efc17776.mp4

**Comment by hamidkhan-o16** [comment]
Done

**Comment by Mustafa016** [comment]
not fixed..

Input field k under jo cursor ara hai woh arabic mai right side sy start hona chahye..
